### ISSUE TITLE
Pesquisa geral sobre Place Code "p-code" na CPLP

### ISSUE THREAD

**Issue by fititnt** [covid-taskforce-cplp/dados-covid#16]
P-code (abreviação de place code) (vide wikipedia <https://en.wikipedia.org/wiki/Place_code> são usados como uma forma de referenciar regiões em datasets no https://data.humdata.org/ e são mencionadas tanto no hxlstandard #9 como são usadas em ferramentas como o hxldash #14 para gerar gráficos a partir de planilhas tageadas.

Numa busca rápida, embora eu consiga encontrar informaçẽs de Angola e Mozambique, isso não é tão intuitivo para códigos do Brasil. Isto é, num primeiro momento eu não consegui encontrar tabelas que permitam fazer cruzamento fácil com códigos usados tipicamente aqui no Brasil, por exemplo
- Códigos do IBGE (https://www.ibge.gov.br/explica/codigos-dos-municipios.php) (extremamente importante)
- Como CEP (https://pt.wikipedia.org/wiki/C%C3%B3digo_postal) (secundário) 

**Esse issue aqui é sobre uma Pesquisa geral sobre Place Code "p-code" na CPLP**, ou ao menos nesse primeiro momento no Brasil. Dependendo do resultado a gente pode tomar alguma ação.

---

Alguns links sobre p-code

- https://en.wikipedia.org/wiki/Place_code
- https://www.humanitarianresponse.info/applications/data/documentation/
- https://wiki.openstreetmap.org/wiki/P-Codes
- https://sites.google.com/site/cimicresources/home/geotools/p-codes
- https://themimu.info/place-codes
- https://www.unece.org/cefact/locode/service/location

**Comment by fititnt** [comment]
- Via https://vocabulary.unocha.org/
  - Download Countries & Territories JSON file
    - http://vocabulary.unocha.org/json/beta-v3/countries.json
  - Countries & Territories spreadsheet https://docs.google.com/spreadsheets/d/1NjSI2LaS3SqbgYc0HdD8oIb7lofGtiHgoKKATCpwVdY/edit#gid=1088874596
      - Copia temporaria (com poder de edição) pelo grupo https://docs.google.com/spreadsheets/d/1prG5r0yEaXXurrhSmay428zT_R_-5C1lwCaD7ZA-NcM/edit#gid=1528390745
  - **PCodes por país https://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External**
    - BRA: não
    - Angola: https://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External/AGO_EN/MapServer
    - CPV: não
    - GNQ: não
    - GNB: não
    - MAC: não
    - Moçambique: https://gistmaps.itos.uga.edu/arcgis/rest/services/COD_External/MOZ_PT/MapServer
    - PRT: não
    - STP: não
    - TLS: não

**Comment by fititnt** [comment]
Ponto de questão pertinente em https://github.com/SimonbJohnson/quickX3/issues/66.

---

Resumidamente: maioria dos países da CPLP não tem P-Codes (exceto por Moçambique e Angola). Eu não sei toda burocracia, mas ao que parece é mais simples se já houve alguma resposta humanitária pela @UN-OCHA.

De qualquer forma, ao menos o hxldash citado em #14 a gente tem abertura para sugerir P-Codes do Brasil baseados nos códigos do IBGE. Isso obviamente não torna sugestão "oficial" como seria feita internamente pela @UN-OCHA, porém pode ser usada informalmente e (se necessário, e bem embasada) acabe virando padrão no futuro.

Porém até aonde sei no momento, ao menos em países que não tenham uma resposta humanitária internacional coordenada, a tendência é não ter esse tipo de padronização de P-Codes, por isso que é compreensível permanecer de forma informal por tempo indefinido. Porém definitivamente ainda é melhor do que a forma atual (que tende a assumir usar talvez nome de cidade e/ou ID ordenado alfabeticamente de nomes de cidade do Brasil, algo definitivamente menos resiliente a alterações futuras).

**Comment by SimonbJohnson** [comment]
To give more information about UNOCHA approach, they will likely be reducing the number of supported countries in the future and so unlikely to support any that are not already supported.

They are lightly considering finding local agencies to decide on the system and maintain them which could then be endorsed/promoted by UNOCHA. So I would suggest going forward with adopting any system coding system in place already.

**Comment by fititnt** [comment]
@SimonbJohnson bom saber disso antecipadamente. Tenho impressão que isso reforça ideia de que além de submeter padrões de P-Codes lá no HXLDash, desenvolvedores de software da CPLP podem começar a tentar promover o ecossistema de ferramentas do HXL localmente. Eventualmente isso pode ser re-validado por agências, mas faz sentido que software e os datasets já existam antes.

---

Ah, um comentário extra que acaba sendo relevante: um grupo de 6 pessoas aqui do @covid-taskforce-cplp / @EticaAI estão considerando submeter até dia 15 de abril de 2020 proposta para o Hackaton Global da UNESCO (https://en.unesco.org/events/codethecurve-hackathon) que justamente envolve promover o ecosistema do HXL nos países da CPLP. Os pontos não estão 100% definidos (e, mesmo que estejam, e o grupo seja aceito no Hachathon, ainda haveria margem para mudar alguns pontos até o dia 24-26 de abril de 2020).

É possível que um dos públicos focos seja justamente pessoas desenvolvedoras de software que, embora já tenham familiaridade com APIs ou mesmo open data, não sabem que o HXL existe. Por exemplo: aqui no Brasil existe uma forte comunidade de software e de open data que poderiam ser replicadores do padrão a nível regional (sem necessariamente depender de uma coordenação internacional) e parece fazer sentido cultivar a ideia de pegar conceitos que já são usados em Moçambique e Angola e aplicar no Brasil. Outro ponto é que países como Brasil tendem a não ter organizações como a UN-OCHA estimulando mais próximo ao publico regional o uso de HXL, e toda pesquisa até chegar no padrão demonstra vantagens técnicas mesmo fora do círculo tradicional do HDX por pessoas que hoje já tem dificuldades em trocas de dados a nível regional, ainda mais em momentos de crise.

Por uma questão de escopo factível em um hackathon de 3 dias (e talvez para evitar assustar a comunidade que entende de software e tecnologia, mas não a fundo da questão humanitária) é possível que a ideia fique mais na questão do próprio padrão e de ferramentas relacionadas já existentes a nível internacional, bem como estimular interoperabilidade de dados e potencial de desenvolvedores que hoje já tem interesse em contribuir com open source considerem desenvolver soluções localizadas na CPLP.

Na minha humilde opinião acredito que o ecossistema do HXL em si poderia (depois de ter lido tanto a respeito) ter hachathon dedicado (assim como existem no passado hackathons de algumas empresas que eram para uso de alguma tecnologia própria deles). Como não tem, da para começar participando de algum hackathon genérico existente.

PS.: talvez você veja eu e/ou colegas interagindo com alguns projetos existentes e quebrando tarefas grandes em pequenas; algumas delas talvez acabem sendo feitas por pessoas do @covid-taskforce-cplp se, e apenas se, não conseguirmos gente que hoje nem faz parte do grupo inicial mas acabe conhecendo em função de divulgação.

**Comment by fititnt** [comment]
Obrigado a todos os envolvidos!!! Uma explicação longa (em Inglês) pode ser lida aqui https://github.com/SimonbJohnson/quickX3/issues/66#issuecomment-737572570.

Os últimos meses estão sendo intensos para todos. Porem em algum momento além dessa referencia nesse issue, vou conversar com as pessoas do @covid-taskforce-cplp.
